version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  adminmongo:
    image: mrvautin/adminmongo
    container_name: mongo_admin
    ports:
      - 1234:1234
    links:
      - mongodb:mongodb
    environment:
      - HOST=0.0.0.0
    depends_on: 
        - mongodb